#!/bin/bash

source /usr/share/fixmycode/.config

# Check if the program is called as "fixmycode"
if [ "$(basename $0)" == "fixmycode" ]; then
  # Clear the console
  clear

  # ASCII banner
  echo "
        ⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⡿⠟⠁⠀⠀⠀⠀⣶⣶⣶⣶⠠⣶⠀⠀⠀⠀⠀⠀⠀⠀⣶⣶⡄⠀⣶⣶⡆⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⢿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⢀⣴⣾⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⣿⣧⣤⣤⢸⣿⠈⢿⣆⣼⡟⠀⠀⠀⣿⣿⣧⢰⡿⣿⡇⢻⣧⢀⣿⠃⠀⠀⠀⠀⠀⠀⠙⢿⣿⣷⣦⡀⠀⠀⠀⠀
        ⠀⠀⢀⣴⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡏⠉⠉⢸⣿⠀⣠⣿⣿⡄⠀⠀⠀⣿⡇⣿⣾⠇⣿⡇⠈⣿⣼⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣦⡀⠀⠀
        ⢀⣴⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠃⠀⠀⠘⠛⠐⠛⠁⠘⠛⠂⠀⠀⠛⠃⠘⠛⠀⠛⠃⢠⣼⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣦⡀
        ⠙⢿⣿⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣤⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣤⠀⠀⠀⠀⠈⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⡿⠋
        ⠀⠀⠙⢿⣿⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⡟⠉⠙⠛⠃⢠⣴⣶⣦⡀⢀⣴⣶⣼⣿⢀⣤⡶⣶⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⡿⠋⠀⠀
        ⠀⠀⠀⠀⠈⠻⣿⣿⣦⣄⠀⠀⠀⠀⠀⠀⠀⠈⣿⣇⠀⢀⣤⡄⣿⡇⠀⣹⡷⢸⣏⠀⢸⣿⢸⣿⠶⢾⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣴⣿⣿⠟⠁⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠈⠻⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠈⠻⠿⠿⠛⠀⠘⠻⠿⠟⠁⠈⠻⠿⠻⠟⠀⠛⠿⠟⠋⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⠟⠁⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀   "
  echo ""
  echo "Welcome to Fix My Code, Created by Aptify#7337, and Powered by OpenAI!"
  echo "         Answer the following prompts to fix your code!               "
  echo ""

  read -p "Enter the programming language: " language

  supported_languages=("python" "javascript" "java" "c" "c++")
  if [[ ! " ${supported_languages[@]} " =~ " $language " ]]; then
    echo "Error: Unsupported programming language"
    exit 1
  fi

  read -p "Enter the name of the file that holds the code: " filename

  if [ ! -f $filename ]; then
    echo "Error: File does not exist"
    exit 1
  fi

  extension="${filename##*.}"
  output_file="${filename%.*}_improved.$extension"

  while IFS= read -r line
    do
      if [[ $line =~ ^#AI.* ]]; then
        # Parse the contents of the file
      fi
    done < "$filename"


  while [ -z "$response" ]; do
  sleep 1
  response=$(curl -X POST -H "Authorization: Bearer $OPENAI_API_KEY" "Content-Type: application/json" -d '{"language":"'"$language"'","code":"'"$(cat $filename)"'"}' https://api.openai.com/v1/engines/code-completion/jobs)
  done


  if [ $? -ne 0 ]; then
  echo "Error: API call failed"
  exit 1
  fi

  response=$(curl -X POST -H "Authorization: Bearer $OPENAI_API_KEY" "Content-Type: application/json" -d '{"language":"'"$language"'","code":"'"$(cat $filename)"'"}' https://api.openai.com/v1/engines/code-completion/jobs)

  improved_code=$(echo $response | jq -r '.choices[0].text')

  echo "$improved_code" > $output_file

  echo "Improved code written to $output_file"
else
  echo "Error: The program must be called as fixmycode"
  exit 1
fi

fixmycode
